#!/usr/bin/env bash
# 7 lines of "1-run_nginx_as_nginx"
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
