#!/usr/bin/env bash
# trying a slightly different method but generally 7 lines of "1-run_nginx_as_nginx" 
pkill apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
