#!/usr/bin/env bash
# load balancer
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend webservers
        balance roundrobin
        server 4822-web-01 52.90.100.15:80 check
        server 4822-web-02 3.208.24.41:80 check
        option httpchk

frontend firstbalance
        bind *:80
        option forwardfor
        default_backend webservers
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
