#!/usr/bin/env bash
# load balancer
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 4822-web-01 18.212.225.222:80 check
        server 4822-web-02 54.147.162.100:80 check

frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
