#!/usr/bin/env bash
# debug to make server listen on port 80

sed -i 's/ipv6only=on//' /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
