#!/usr/bin/env bash
# short version of 0-nginx_likes_port_80:- Fixes the nginx listening port and reloads the nginx master process
echo -e "sed -iE 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default\
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho''> /run/nginx.pid" | bash
